# /**************************************************************************/
# /*  gdscript_converter.py                                                 */
# /**************************************************************************/
# /*                         This file is part of:                          */
# /*                             GAME ENGINE                                */
# /**************************************************************************/

"""GDScript to Python converter for automatic script migration."""

import re
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import logging



logger = logging.getLogger(__name__)

class GDScriptConverter:
    """Converts GDScript files to Python scripts."""
    
    def __init__(self):
        self.conversions = 0
        self.errors: List[str] = []
    
    def convert_file(self, gd_path: str) -> Optional[str]:
        """Convert a .gd file to Python and return the Python code."""
        path = Path(gd_path)
        if not path.exists():
            self.errors.append(f"File not found: {gd_path}")
            return None
        
        try:
            gd_code = path.read_text(encoding='utf-8')
            return self.convert_code(gd_code, path.stem)
        except Exception as e:
            self.errors.append(f"Error readin         g {gd_path}: {e}")
            return None
    
    def convert_code(self, gd_code: str, class_name: str = "Script") -> str:
        """Convert GDScript code to Python."""
        python_code = []
        
        # Add header
        python_code.append(f"# Converted from GDScript: {class_name}")
        python_code.append("# Auto-generated by Game Engine Studio")
        python_code.append("")
        python_code.append("from engine.core.node_base import Node2D")
        python_code.append("from engine.core.signals import SignalBus")
        python_code.append("")
        
        # Parse GDScript class
        lines = gd_code.split('\n')
        
        # Extract class name and extends
        class_info = self._parse_class_declaration(lines)
        
        # Convert to Python class
        python_code.append(f"class {class_info['name']}(Node2D):")
        python_code.append('    """Auto-converted GDScript class."""')
        python_code.append("")
        
        # Convert exports/variables
        for var_line in self._extract_exports(lines):
            py_var = self._convert_export(var_line)
            python_code.append(f"    {py_var}")
        
        python_code.append("")
        
        # Convert functions
        funcs = self._extract_functions(gd_code)
        for func_name, func_code in funcs.items():
            py_func = self._convert_function(func_name, func_code)
            python_code.append(py_func)
            python_code.append("")
        
        return '\n'.join(python_code)
    
    def _parse_class_declaration(self, lines: List[str]) -> Dict:
        """Parse class declaration from GDScript."""
        info = {'name': 'MyScript', 'extends': 'Node2D'}
        
        for line in lines:
            line = line.strip()
            if line.startswith('class_name '):
                info['name'] = line.split()[1]
            elif line.startswith('extends '):
                info['extends'] = line.split()[1]
        
        return info
    
    def _extract_exports(self, lines: List[str]) -> List[str]:
        """Extract @export variable declarations."""
        exports = []
        for line in lines:
            stripped = line.strip()
            if stripped.startswith('@export'):
                exports.append(stripped)
        return exports
    
    def _convert_export(self, export_line: str) -> str:
        """Convert @export var to Python attribute."""
        # Remove @export and parse
        line = re.sub(r'@export\s*', '', export_line)
        
        # Handle onready exports
        if '@onready' in line:
            line = re.sub(r'@onready\s*@export\s*', '', line)
        
        # Parse var declaration
        # var name: Type = value
        match = re.match(r'var\s+(\w+)\s*(?::\s*(\w+))?\s*(?:=\s*(.+))?\s*$', line)
        if match:
            name, type_hint, value = match.groups()
            if value:
                # Convert value
                py_value = self._convert_value(value)
                return f"{name} = {py_value}"
            else:
                return f"{name} = None"
        
        return f"# TODO: Convert {export_line}"
    
    def _extract_functions(self, code: str) -> Dict[str, str]:
        """Extract functions from GDScript."""
        funcs = {}
        
        # Find all func declarations
        pattern = r'func\s+(\w+)\s*\([^)]*\).*?(?=(?:(?:func|class_name|extends)\s+)|$)'
        matches = re.finditer(pattern, code, re.DOTALL)
        
        for match in matches:
            func_header = match.group(0)
            func_name = re.search(r'func\s+(\w+)', func_header).group(1)
            funcs[func_name] = func_header
        
        return funcs
    
    def _convert_function(self, name: str, code: str) -> str:
        """Convert GDScript function to Python."""
        lines = []
        
        # Parse signature
        sig_match = re.search(r'func\s+\w+\s*\((.*)\)', code)
        if sig_match:
            params = sig_match.group(1).strip()
            # Convert GDScript type hints to Python
            params = self._convert_params(params)
        else:
            params = "self"
        
        if not params.startswith('self'):
            params = f"self, {params}"
        
        lines.append(f"    def {name}({params}):")
        
        # Extract body
        body_match = re.search(r':\s*\n(.*)', code, re.DOTALL)
        if body_match:
            body = body_match.group(1)
            py_body = self._convert_body(body)
            for line in py_body.split('\n'):
                lines.append(f"        {line}")
        else:
            lines.append("        pass")
        
        return '\n'.join(lines)
    
    def _convert_params(self, params: str) -> str:
        """Convert GDScript parameters to Python."""
        if not params:
            return "self"
        
        result = []
        for param in params.split(','):
            param = param.strip()
            # Remove type hints
            param = re.sub(r':\s*\w+', '', param)
            # Handle default values
            param = re.sub(r'=\s*([\w"\']+)', r'=\1', param)
            result.append(param)
        
        return ', '.join(result)
    
    def _convert_body(self, body: str) -> str:
        """Convert GDScript function body to Python."""
        lines = []
        
        for line in body.split('\n'):
            stripped = line.strip()
            if not stripped:
                continue
            
            # Skip comments but keep them
            if stripped.startswith('#'):
                lines.append(stripped)
                continue
            
            # Remove inline comments temporarily
            comment = ""
            if '#' in stripped:
                idx = stripped.index('#')
                comment = stripped[idx:]
                stripped = stripped[:idx].strip()
            
            # Convert GDScript booleans to Python
            stripped = re.sub(r'\btrue\b', 'True', stripped)
            stripped = re.sub(r'\bfalse\b', 'False', stripped)
            
            # Convert null to None
            stripped = re.sub(r'\bnull\b', 'None', stripped)
            
            # Convert super call
            stripped = re.sub(r'super\.(\w+)\(\)', r'super().\1()', stripped)
            
            # Convert $NodePath to self.find_child
            stripped = re.sub(r'\$([\w/]+)', r'self.find_child("\1")', stripped)
            
            # Convert get_node() to self.find_child
            stripped = re.sub(r'get_node\("([^"]+)"\)', r'self.find_child("\1")', stripped)
            
            # Remove var keyword (GDScript var x = 5 → Python x = 5)
            stripped = re.sub(r'\bvar\s+', '', stripped)
            
            # Convert await (Python uses different async model)
            stripped = re.sub(r'\bawait\s+', '', stripped)
            
            # Convert signal connections
            stripped = re.sub(r'\.connect\("([^"]+)"\s*,\s*', r'.signals.connect("\1", ', stripped)
            
            # Convert global position
            stripped = re.sub(r'\bglobal_position\b', 'self.position', stripped)
            
            # Convert velocity
            stripped = re.sub(r'\bvelocity\b', 'self.velocity', stripped)
            
            # Convert delta (common in _process)
            stripped = re.sub(r'\bdelta\b', 'delta', stripped)
            
            # Convert Input.is_action_pressed
            stripped = re.sub(r'Input\.is_action_pressed\("([^"]+)"\)', 
                            r'self.is_action_pressed("\1")', stripped)
            stripped = re.sub(r'Input\.is_action_just_pressed\("([^"]+)"\)', 
                            r'self.is_action_just_pressed("\1")', stripped)
            
            # Convert move_and_slide
            stripped = re.sub(r'\bmove_and_slide\(\)', 'self.move_and_slide()', stripped)
            
            # Convert pass (GDScript uses 'pass', Python also uses 'pass' - same!)
            # No change needed
            
            # Add comment back
            if comment:
                stripped = f"{stripped}  {comment}"
            
            lines.append(stripped)
        
        return '\n'.join(lines)
    
    def _convert_value(self, value: str) -> str:
        """Convert GDScript value to Python."""
        value = value.strip()
        
        # Vector2
        if value.startswith('Vector2'):
            match = re.search(r'Vector2\(([^,]+),\s*([^)]+)\)', value)
            if match:
                return f"({match.group(1)}, {match.group(2)})"
        
        # Color
        if value.startswith('Color'):
            return "(1.0, 1.0, 1.0, 1.0)"  # Default white
        
        # NodePath
        if value.startswith('^'):
            return f'"{value[1:]}"'
        
        # Strings and numbers pass through
        return value


def convert_gdscript_to_python(gd_path: str) -> Optional[str]:
    """Convert a GDScript file to Python."""
    converter = GDScriptConverter()
    return converter.convert_file(gd_path)


def convert_gdscript_in_project(project_path: Path) -> Dict[str, str]:
    """Find and convert all .gd files in project to Python."""
    converter = GDScriptConverter()
    converted = {}
    
    # Find all .gd files
    for gd_file in project_path.rglob("*.gd"):
        try:
            py_code = converter.convert_file(str(gd_file))
            if py_code:
                # Save to converted_scripts folder
                scripts_dir = project_path / "converted_scripts"
                scripts_dir.mkdir(exist_ok=True)
                
                py_path = scripts_dir / f"{gd_file.stem}.py"
                py_path.write_text(py_code, encoding='utf-8')
                converted[str(gd_file)] = str(py_path)
        except Exception as e:
            print(f"Failed to convert {gd_file}: {e}")
    
    return converted


# Example usage
if __name__ == "__main__":
    # Test conversion
    test_gd = '''
class_name Player
extends CharacterBody2D

@export var speed: float = 200.0
@export var health: int = 100

@onready var sprite = $Sprite2D

func _ready():
    position = Vector2(100, 100)
    
func _process(delta):
    velocity = Vector2.ZERO
    if Input.is_action_pressed("ui_right"):
        velocity.x = speed
    move_and_slide()
'''
    
    converter = GDScriptConverter()
    result = converter.convert_code(test_gd, "TestScript")
    print(result)
